#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

$OPENSHIFT_REPO_DIR/gradlew build -x test

nohup java -Dserver.port=$OPENSHIFT_DIY_PORT $JAVA_OPTS -Dspring.profiles.active=openshift -jar $OPENSHIFT_REPO_DIR/build/libs/*aqarme-*.jar &

#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &
